SukiSU-Ultra
Add SukiSU and Bump Susfs version to v1.5.10

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -28,23 +28,23 @@ jobs:
 
       - name: "💡 Setup KernelSu"
         run: |
-          if [ -d "./KernelSU-Next" ]; then rm -rf "./KernelSU-Next"; fi
-          if [ -d "./drivers/KernelSU-Next" ]; then rm -rf "./drivers/KernelSU-Next"; fi 
-          curl -LSs "https://raw.githubusercontent.com/Star-Seven/KernelSU-Next/next/kernel/setup.sh" | bash -
+          if [ -d "./KernelSU" ]; then rm -rf "./KernelSU"; fi
+          if [ -d "./drivers/KernelSU" ]; then rm -rf "./drivers/KernelSU"; fi 
+          curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s susfs-main  || exit 1
 
       - name: "😄 Setup and Apply susfs4ksu Patches"
         run: |
            set -e
 
            # Backport SUSFS to Linux 4.14
-           git clone https://github.com/Star-Seven/susfs4ksu -b M62-backport-1.5.9 susfs4ksu-repo
+           git clone https://github.com/Star-Seven/susfs4ksu -b M62-backport-1.5.10 susfs4ksu-repo
 
-           cp susfs4ksu-repo/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch ./KernelSU-Next/
+           # cp susfs4ksu-repo/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch ./KernelSU-Next/
            cp susfs4ksu-repo/kernel_patches/fs/* fs/
            cp susfs4ksu-repo/kernel_patches/include/linux/* include/linux/
-           cd ./KernelSU-Next
-           patch -p1 -F 3 < 10_enable_susfs_for_ksu.patch || { echo "Failed to apply patch"; exit 1; }
-           cd ..
+           # cd ./KernelSU
+           # patch -p1 -F 3 < 10_enable_susfs_for_ksu.patch || { echo "Failed to apply patch"; exit 1; }
+           # cd ..
            patch -p1 --verbose < susfs4ksu-repo/kernel_patches/50_add_susfs_in_kernel-4.14.patch
            echo "Successfully applied susfs4ksu patches"
 
